unset LD_PRELOAD
export TORCH_CUDA_ARCH_LIST='7.0;7.5;8.0;8.6;8.9;9.0'
INTERNAL_VERSION=${1}
if [ -z ${INTERNAL_VERSION} ];then
    INTERNAL_VERSION=1
fi
echo "INTERNAL_VERSION=$INTERNAL_VERSION"
export INTERNAL_VERSION=${INTERNAL_VERSION}
python setup.py bdist_wheel 
